#!/bin/bash

# EXPLICACIÓN COMPLETA: Cómo Funcionan tus Contenedores
# Este script te muestra cada componente y cómo se comunican

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  🐳 EXPLICACIÓN: ARQUITECTURA DE CONTENEDORES                  ║"
echo "║     Sistema Invernadero - Cómo Funciona Todo                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# PARTE 1: Estructura General
echo "┌─ PARTE 1: ¿QUÉ SON LOS CONTENEDORES? ─────────────────────────┐"
echo "│                                                                │"
echo "│ Un contenedor es como una CAJA sellada que contiene:          │"
echo "│                                                                │"
echo "│ 1. Sistema operativo (Linux mínimo)                           │"
echo "│ 2. Tu aplicación                                              │"
echo "│ 3. Todas las dependencias que necesita                        │"
echo "│ 4. Configuración y variables de entorno                       │"
echo "│                                                                │"
echo "│ ✅ VENTAJA: Funciona igual en tu PC, en AWS, en Google Cloud │"
echo "│            No importa qué OS tengas                           │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 2: Tus Contenedores
echo "┌─ PARTE 2: TUS 4 CONTENEDORES ─────────────────────────────────┐"
echo "│                                                                │"
echo "│ 📦 CONTENEDOR 1: TIMESCALEDB (Base de Datos)                 │"
echo "│    ├─ Imagen: timescale/timescaledb:latest-pg15             │"
echo "│    ├─ Puerto: 5432 (interno) → 5432 (tu PC)                 │"
echo "│    ├─ Qué hace:                                              │"
echo "│    │  • Guarda datos de sensores                             │"
echo "│    │  • Tabla: mediciones (temperatura, humedad, etc)        │"
echo "│    │  • Optimizado para datos de tiempo (TimescaleDB)        │"
echo "│    └─ Acceso: psql -h localhost -U admin -d invernadero_db  │"
echo "│                                                                │"
echo "│ 📦 CONTENEDOR 2: RABBITMQ (Message Broker)                   │"
echo "│    ├─ Imagen: rabbitmq:3.13-management-alpine               │"
echo "│    ├─ Puertos: 5672 (AMQP) + 15672 (Management UI)           │"
echo "│    ├─ Qué hace:                                              │"
echo "│    │  • Distribuye mensajes entre servicios                  │"
echo "│    │  • Exchange: invernadero.telemetry.exchange             │"
echo "│    │  • Queues: alarm.queue, persistence.queue               │"
echo "│    │  • Si el backend falla, los mensajes quedan en cola     │"
echo "│    └─ Acceso: http://localhost:15672 (guest/guest)          │"
echo "│                                                                │"
echo "│ 📦 CONTENEDOR 3: BACKEND (Spring Boot API)                   │"
echo "│    ├─ Imagen: sistemainvernadero-backend:latest             │"
echo "│    ├─ Puerto: 8080 (interno) → 8080 (tu PC)                 │"
echo "│    ├─ Qué hace:                                              │"
echo "│    │  • Recibe datos de sensores (POST /api/v1/ingest)       │"
echo "│    │  • Publica en RabbitMQ                                  │"
echo "│    │  • Consulta database (GET /api/v1/analytics/dashboard)  │"
echo "│    │  • Procesa alertas si temperatura > 35°C                │"
echo "│    └─ Lenguaje: Java 17 con Spring Boot                      │"
echo "│                                                                │"
echo "│ 📦 CONTENEDOR 4: FRONTEND (React App) - EN TU PC (no Docker) │"
echo "│    ├─ Tecnología: Node.js + Vite + React                     │"
echo "│    ├─ Puerto: 3000                                            │"
echo "│    ├─ Qué hace:                                              │"
echo "│    │  • Muestra dashboard con gráficos                       │"
echo "│    │  • Botones para enviar datos (Ingestion panel)          │"
echo "│    │  • Consume API del backend vía proxy                    │"
echo "│    │  • Hot reload (recarga automática si cambias código)    │"
echo "│    └─ 4 Tabs: Dashboard, Ingestion, Sensors, Alerts          │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 3: Cómo se Comunican
echo "┌─ PARTE 3: FLUJO DE DATOS ─────────────────────────────────────┐"
echo "│                                                                │"
echo "│ ESCENARIO: Envías datos desde Frontend                        │"
echo "│                                                                │"
echo "│ 1. TÚ haces click en \"Send Telemetry\" en http://localhost:3000│"
echo "│                                                                │"
echo "│ 2. FRONTEND (React)                                           │"
echo "│    └─ Envía POST a http://localhost:8080/api/v1/ingest       │"
echo "│       Datos: {greenhouse: GW-001, sensor: S01, temp: 25.5}   │"
echo "│                                                                │"
echo "│ 3. BACKEND (Spring Boot)                                      │"
echo "│    ├─ Recibe el POST                                          │"
echo "│    ├─ Valida datos                                            │"
echo "│    └─ Publica en RabbitMQ con routing key:                    │"
echo "│        \"invernadero.GW-001.S01\"                             │"
echo "│                                                                │"
echo "│ 4. RABBITMQ (Message Broker)                                  │"
echo "│    ├─ Recibe el mensaje                                       │"
echo "│    ├─ Lo copia a 2 queues:                                    │"
echo "│    │  • alarm.queue (para detectar alertas)                   │"
echo "│    │  • persistence.queue (para guardar en DB)                │"
echo "│    └─ Garantiza que no se pierden datos                       │"
echo "│                                                                │"
echo "│ 5a. AlarmService (Backend Thread)                             │"
echo "│    ├─ Consume de alarm.queue                                  │"
echo "│    ├─ Chequea: ¿temperatura > 35°C?                           │"
echo "│    └─ Si SÍ: Registra alerta (log)                            │"
echo "│                                                                │"
echo "│ 5b. PersistenceService (Backend Thread)                       │"
echo "│    ├─ Consume de persistence.queue                            │"
echo "│    ├─ Guarda en TimescaleDB:                                  │"
echo "│    │  INSERT INTO mediciones (                                │"
echo "│    │    sensor_id, temperature, humidity,                     │"
echo "│    │    greenhouse_id, timestamp                              │"
echo "│    │  ) VALUES (...)                                          │"
echo "│    └─ Datos ahora persistidos                                 │"
echo "│                                                                │"
echo "│ 6. TÚ haces click en \"Dashboard\" tab                         │"
echo "│                                                                │"
echo "│ 7. FRONTEND (React)                                           │"
echo "│    └─ Hace GET http://localhost:8080/api/v1/analytics/...    │"
echo "│                                                                │"
echo "│ 8. BACKEND (Spring Boot)                                      │"
echo "│    ├─ Consulta TimescaleDB:                                   │"
echo "│    │  SELECT * FROM mediciones                                │"
echo "│    │  WHERE greenhouse_id = 'GW-001'                          │"
echo "│    │  AND timestamp > NOW() - 24 hours                        │"
echo "│    ├─ Calcula: promedio temperatura                           │"
echo "│    └─ Retorna JSON con datos                                  │"
echo "│                                                                │"
echo "│ 9. FRONTEND (React)                                           │"
echo "│    ├─ Recibe JSON                                             │"
echo "│    ├─ Dibuja gráficos con Recharts                            │"
echo "│    └─ Muestra KPI cards (promedio, alertas, sensores)         │"
echo "│                                                                │"
echo "│ 10. TÚ VES los datos en la pantalla                           │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 4: Networking
echo "┌─ PARTE 4: RED INTERNA (Docker Network) ───────────────────────┐"
echo "│                                                                │"
echo "│ Todos los contenedores están en la misma RED (bridge network) │"
echo "│ Esto permite que se comuniquen POR NOMBRE:                    │"
echo "│                                                                │"
echo "│ Backend puede conectar a TimescaleDB así:                     │"
echo "│   jdbc:postgresql://timescaledb:5432/invernadero_db           │"
echo "│   ├─ timescaledb = nombre del contenedor                      │"
echo "│   ├─ 5432 = puerto INTERNO (no el 5432 de tu PC)              │"
echo "│   └─ Docker lo traduce automáticamente a IP correcta          │"
echo "│                                                                │"
echo "│ Backend puede conectar a RabbitMQ así:                        │"
echo "│   amqp://guest:guest@rabbitmq:5672                            │"
echo "│   ├─ rabbitmq = nombre del contenedor                         │"
echo "│   └─ 5672 = puerto AMQP INTERNO                               │"
echo "│                                                                │"
echo "│ TÚ desde tu PC haces:                                          │"
echo "│   http://localhost:8080 (Backend)                             │"
echo "│   http://localhost:3000 (Frontend)                            │"
echo "│   http://localhost:15672 (RabbitMQ UI)                        │"
echo "│   localhost:5432 (PostgreSQL)                                 │"
echo "│                                                                │"
echo "│ Los PUERTOS se mapean:                                        │"
echo "│   Contenedor:5432 → Tu PC:5432  (docker-compose.yml)          │"
echo "│   Contenedor:15672 → Tu PC:15672 (docker-compose.yml)         │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 5: Volúmenes
echo "┌─ PARTE 5: VOLÚMENES (Persistencia de Datos) ──────────────────┐"
echo "│                                                                │"
echo "│ Sin volúmenes: Si eliminas el contenedor, pierdes TODO        │"
echo "│ Con volúmenes: Los datos quedan guardados en tu PC            │"
echo "│                                                                │"
echo "│ TUS VOLÚMENES:                                                │"
echo "│                                                                │"
echo "│ postgres_data (TimescaleDB)                                   │"
echo "│ ├─ Guardar en: Docker's internal storage                      │"
echo "│ ├─ Datos: Toda la base de datos                               │"
echo "│ └─ Si borras contenedor → datos quedan → reinicio restaura    │"
echo "│                                                                │"
echo "│ rabbitmq_data (RabbitMQ)                                      │"
echo "│ ├─ Guardar en: Docker's internal storage                      │"
echo "│ ├─ Datos: Mensajes en queues                                  │"
echo "│ └─ Garantiza que no pierdes mensajes pendientes               │"
echo "│                                                                │"
echo "│ COMANDO para ver volúmenes:                                   │"
echo "│   docker volume ls                                            │"
echo "│                                                                │"
echo "│ COMANDO para inspeccionar un volumen:                         │"
echo "│   docker volume inspect sistemainvernadero_postgres_data      │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 6: Estados
echo "┌─ PARTE 6: ESTADOS DE UN CONTENEDOR ───────────────────────────┐"
echo "│                                                                │"
echo "│ running     = Contenedor activo, ejecutando                   │"
echo "│ exited      = Se detuvo (error o comando completado)          │"
echo "│ restarting  = Tratando de reiniciar                           │"
echo "│ paused      = En pausa (congelado)                            │"
echo "│ created     = Creado pero nunca ejecutado                     │"
echo "│                                                                │"
echo "│ Ver estado actual:                                            │"
echo "│   docker-compose ps                                           │"
echo "│                                                                │"
echo "│ Ver histórico:                                                │"
echo "│   docker ps -a                                                │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 7: Logs
echo "┌─ PARTE 7: LOGS (Ver qué está pasando) ────────────────────────┐"
echo "│                                                                │"
echo "│ Los contenedores escriben TODO a stdout/stderr                │"
echo "│ Docker captura eso en logs                                    │"
echo "│                                                                │"
echo "│ Ver logs en tiempo real:                                      │"
echo "│   docker-compose logs -f backend                              │"
echo "│   docker-compose logs -f timescaledb                          │"
echo "│   docker-compose logs -f rabbitmq                             │"
echo "│                                                                │"
echo "│ Ver últimas 100 líneas:                                       │"
echo "│   docker-compose logs --tail=100 backend                      │"
echo "│                                                                │"
echo "│ Ver logs de contenedor específico:                            │"
echo "│   docker logs <container_id>                                  │"
echo "│                                                                │"
echo "│ Ver logs con timestamps:                                      │"
echo "│   docker-compose logs -t backend                              │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 8: Lifecycle
echo "┌─ PARTE 8: CICLO DE VIDA ──────────────────────────────────────┐"
echo "│                                                                │"
echo "│ CREACIÓN:                                                     │"
echo "│ 1. docker-compose build                                       │"
echo "│    └─ Construye imagen desde Dockerfile                       │"
echo "│                                                                │"
echo "│ 2. docker-compose up -d                                       │"
echo "│    ├─ Crea contenedores                                       │"
echo "│    ├─ Inicia servicios                                        │"
echo "│    └─ Los mantiene corriendo                                  │"
echo "│                                                                │"
echo "│ DURANTE EJECUCIÓN:                                            │"
echo "│ • Procesos en el contenedor ejecutan                          │"
echo "│ • Pueden escribir a stdout (se captura en logs)                │"
echo "│ • Pueden crear archivos (en volúmenes persisten)              │"
echo "│ • Pueden escuchar en puertos                                  │"
echo "│                                                                │"
echo "│ PARADA:                                                       │"
echo "│ 1. docker-compose stop                                        │"
echo "│    └─ Envía SIGTERM (kill suave)                              │"
echo "│                                                                │"
echo "│ 2. docker-compose down                                        │"
echo "│    ├─ Para contenedores                                       │"
echo "│    ├─ Elimina red                                             │"
echo "│    └─ Pero MANTIENE volúmenes (datos persisten)               │"
echo "│                                                                │"
echo "│ 3. docker-compose down -v                                     │"
echo "│    └─ Elimina TODO incluyendo volúmenes (⚠️  pierdes datos)   │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 9: Comandos útiles
echo "┌─ PARTE 9: COMANDOS ÚTILES ────────────────────────────────────┐"
echo "│                                                                │"
echo "│ Ver todo:                                                     │"
echo "│   docker ps                          # Contenedores corriendo │"
echo "│   docker ps -a                       # Todos los contenedores │"
echo "│   docker images                      # Imágenes disponibles   │"
echo "│   docker volume ls                   # Volúmenes             │"
echo "│   docker network ls                  # Redes                 │"
echo "│                                                                │"
echo "│ Inspeccionar:                                                 │"
echo "│   docker inspect <container>         # Info del contenedor    │"
echo "│   docker logs <container>            # Logs del contenedor    │"
echo "│   docker exec <container> ls         # Ver archivos adentro   │"
echo "│   docker stats                       # Uso de CPU/memoria     │"
echo "│                                                                │"
echo "│ Conectarse:                                                   │"
echo "│   docker exec -it <container> bash   # Shell en contenedor    │"
echo "│   docker exec -it <container> sh     # Shell alternativo      │"
echo "│                                                                │"
echo "│ Limpiar:                                                      │"
echo "│   docker system prune                # Elimina todo no usado  │"
echo "│   docker system df                   # Uso de espacio         │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

# PARTE 10: Resumen
echo "┌─ PARTE 10: RESUMEN ───────────────────────────────────────────┐"
echo "│                                                                │"
echo "│ ✅ 4 contenedores = 1 aplicación completa                     │"
echo "│ ✅ Se comunican por red Docker (interna)                      │"
echo "│ ✅ Puertos mapeados para acceso desde tu PC                   │"
echo "│ ✅ Datos persistidos en volúmenes                             │"
echo "│ ✅ Logs capturados y accesibles                               │"
echo "│ ✅ Aislamiento = no interfieren con tu sistema                │"
echo "│                                                                │"
echo "│ CUANDO HACES:                                                 │"
echo "│                                                                │"
echo "│ docker-compose up → Docker:                                  │"
echo "│ 1. Verifica que imágenes existan (sino las descarga)          │"
echo "│ 2. Crea red interna                                           │"
echo "│ 3. Crea volúmenes (si no existen)                             │"
echo "│ 4. Inicia 4 contenedores en paralelo                          │"
echo "│ 5. Todos están conectados en la MISMA red                     │"
echo "│ 6. Se comunican por nombre (DNS interno)                      │"
echo "│ 7. Tú accedes desde localhost:puerto                          │"
echo "│                                                                │"
echo "└────────────────────────────────────────────────────────────────┘"
echo ""

echo "🎓 ¿Preguntas?  Usa: docker-compose ps, docker logs, docker inspect"
echo ""
