apiVersion: v1
kind: ConfigMap
metadata:
  name: invernadero-backend-config
  namespace: invernadero
data:
  SPRING_APPLICATION_JSON: |
    {
      "server": {
        "port": 8080
      },
      "spring": {
        "datasource": {
          "url": "jdbc:postgresql://timescaledb-service:5432/invernadero_db"
        },
        "rabbitmq": {
          "host": "rabbitmq-service",
          "port": 5672
        },
        "sql": {
          "init": {
            "mode": "always"
          }
        }
      },
      "management": {
        "endpoints": {
          "web": {
            "exposure": {
              "include": "health,info"
            }
          }
        },
        "endpoint": {
          "health": {
            "probes": {
              "enabled": true
            }
          }
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: invernadero-db-secret
  namespace: invernadero
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: "invernadero-secure-password-change-me"
  POSTGRES_DB: invernadero_db
---
apiVersion: v1
kind: Secret
metadata:
  name: invernadero-rabbitmq-secret
  namespace: invernadero
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: invernadero
  RABBITMQ_DEFAULT_PASS: "rabbitmq-secure-password-change-me"
